-- Migration 008: Criar tabelas agendamentos e ordens_servico
-- Fase 3 - passo 6a: agendamentos + geração de OS
-- Data: 2026-06-23

CREATE TABLE IF NOT EXISTS `agendamentos` (
  `id` char(36) NOT NULL DEFAULT (UUID()),
  `proposta_id` char(36) DEFAULT NULL,
  `embarcacao_id` char(36) NOT NULL,
  `cliente_id` char(36) NOT NULL,
  `vistoriador_id` char(36) DEFAULT NULL,
  `vendedor_id` char(36) DEFAULT NULL,
  `tipo_vistoria` varchar(150) NOT NULL,
  `data_vistoria` date NOT NULL,
  `hora_vistoria` time DEFAULT NULL,
  `local` varchar(255) DEFAULT NULL,
  `contato_nome` varchar(150) DEFAULT NULL,
  `contato_telefone` varchar(30) DEFAULT NULL,
  `status` enum('pendente','confirmado','em_andamento','concluido','cancelado') NOT NULL DEFAULT 'pendente',
  `observacoes` text DEFAULT NULL,
  `criado_por` char(36) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `proposta_id` (`proposta_id`),
  KEY `embarcacao_id` (`embarcacao_id`),
  KEY `cliente_id` (`cliente_id`),
  KEY `vistoriador_id` (`vistoriador_id`),
  KEY `status` (`status`),
  KEY `data_vistoria` (`data_vistoria`),
  KEY `criado_por` (`criado_por`),
  CONSTRAINT `agendamentos_ibfk_1` FOREIGN KEY (`proposta_id`) REFERENCES `propostas` (`id`) ON DELETE SET NULL,
  CONSTRAINT `agendamentos_ibfk_2` FOREIGN KEY (`embarcacao_id`) REFERENCES `embarcacoes` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `agendamentos_ibfk_3` FOREIGN KEY (`cliente_id`) REFERENCES `clientes` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `agendamentos_ibfk_4` FOREIGN KEY (`vistoriador_id`) REFERENCES `usuarios` (`id`) ON DELETE SET NULL,
  CONSTRAINT `agendamentos_ibfk_5` FOREIGN KEY (`criado_por`) REFERENCES `usuarios` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `ordens_servico` (
  `id` char(36) NOT NULL DEFAULT (UUID()),
  `numero` varchar(30) NOT NULL,
  `agendamento_id` char(36) NOT NULL,
  `proposta_id` char(36) DEFAULT NULL,
  `embarcacao_id` char(36) NOT NULL,
  `cliente_id` char(36) NOT NULL,
  `vistoriador_id` char(36) NOT NULL,
  `tipo_vistoria` varchar(150) NOT NULL,
  `data_vistoria` date NOT NULL,
  `hora_vistoria` time DEFAULT NULL,
  `local` varchar(255) DEFAULT NULL,
  `contato_nome` varchar(150) DEFAULT NULL,
  `contato_telefone` varchar(30) DEFAULT NULL,
  `status` enum('pendente','em_andamento','executado','cancelado') NOT NULL DEFAULT 'pendente',
  `observacoes` text DEFAULT NULL,
  `criado_por` char(36) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `numero` (`numero`),
  UNIQUE KEY `agendamento_id` (`agendamento_id`),
  KEY `proposta_id` (`proposta_id`),
  KEY `embarcacao_id` (`embarcacao_id`),
  KEY `cliente_id` (`cliente_id`),
  KEY `vistoriador_id` (`vistoriador_id`),
  KEY `status` (`status`),
  KEY `data_vistoria` (`data_vistoria`),
  KEY `criado_por` (`criado_por`),
  CONSTRAINT `ordens_servico_ibfk_1` FOREIGN KEY (`agendamento_id`) REFERENCES `agendamentos` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `ordens_servico_ibfk_2` FOREIGN KEY (`proposta_id`) REFERENCES `propostas` (`id`) ON DELETE SET NULL,
  CONSTRAINT `ordens_servico_ibfk_3` FOREIGN KEY (`embarcacao_id`) REFERENCES `embarcacoes` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `ordens_servico_ibfk_4` FOREIGN KEY (`cliente_id`) REFERENCES `clientes` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `ordens_servico_ibfk_5` FOREIGN KEY (`vistoriador_id`) REFERENCES `usuarios` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `ordens_servico_ibfk_6` FOREIGN KEY (`criado_por`) REFERENCES `usuarios` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;